### ISSUE TITLE
add ISO 639-3

### ISSUE THREAD

**Issue by Pantyhose-X** [toaq/toaq.github.io#33]
https://glottolog.org/resource/languoid/id/ling1267
https://iso639-3.sil.org/

https://github.com/apertium/apertium-init

**Comment by lynn** [comment]
Currently we have `qtq` in http://www.kreativekorp.com/clcr/ . I don't think we need a "real" ISO code, and given that some vastly more popular conlangs don't have one, I feel like we would just get rejected.
